const fs = require("fs");
const create = require("./create.js");
require("dotenv").config();
require("./utils/console.js");

// Since "source" deprecated, i'll use ShareX server to upload the image.
// Thanks, sxcu.net
const sxcuPath = "configs/uploader.sxcu";
const sxcu = (fs.existsSync(sxcuPath))
    ? JSON.parse(fs.readFileSync(sxcuPath, { encoding: "utf8" }))
    : null;

// Main Function
(main = async () => {
    // Data for current episode.
    // Auto-generated by create.js
    const dataPath = "configs/data.json";
    const data = (fs.existsSync(dataPath))
        ? JSON.parse(fs.readFileSync(dataPath, { encoding: "utf8" }))
        : null;
    
    // Check if data and sxcu are exist
    if (!data || !sxcu) {
        console.error("Data file or sxcu file not exist. Exiting...");
        process.exit(1);
    }
    
    const episodeWithPad = data.current_episode.toString().padStart(2, "0"); // Output example: XX
    const frameWithPad = data.current_frame.toString().padStart(4, "0"); // Output example: XXXX
    
    // Check if all frames posted.
    // If that happends, call create.js with parameter (data.current_episode + 1).
    // But make sure the anime file is exist
    if (data.current_frame > data.max_frame) {
        console.warn("Episode " + episodeWithPad + " is completed! Checking new anime...");
        
        // Check for another episode
        if (data.current_episode >= data.max_episode) {
            console.log("No more episode available. I think that's the end.");
            process.exit(0);
        } else {
            // Still has episode, call create.
            create(data.current_episode + 1);
        }
        
        // Call main again.
        main();
        return;
    }
    
    const fileName = `${episodeWithPad}_${frameWithPad}.jpeg`; // Frame file format: XX_YYYY.jpeg
    const framePath = `frames/${fileName}`;
    
    const formData = new FormData();
    const sxcuData = new FormData();
    
    try {
        console.log(`Episode ${episodeWithPad} - Frame ${data.current_frame}/${data.max_frame} is publishing...`);
        
        // Check if the frame file exist.
        // Call main() again to try to post another one if not exist.
        if (!fs.existsSync(framePath)) {
            console.warn(fileName + " is not exist. Trying another next frame...");
            updateData(data, dataPath);
            main();
            
            return;
        }
        
        // For sxcu
        const file = fs.readFileSync(framePath);
        sxcuData.append(sxcu.FileFormName, new Blob([file]), fileName);
        if (sxcu.Arguments) for (const prop in sxcu.Arguments) {
            sxcuData.append(prop, sxcu.Arguments[prop]);
        }
        
        // Upload frame to ShareX server
        const sxRes = await fetch(sxcu.RequestURL, {
            method: sxcu.RequestMethod || "POST",
            body: sxcuData
        }).then(r => r.json());
        if (!sxRes.url) throw new Error("No image url.");
        
        // Caption for post
        const caption = 
            `Episode ${episodeWithPad}` // Episode
            + " - "
            + `Frame ${data.current_frame} out of ${data.max_frame}\n` // Frame
            + `#ESSFIOEPS${data.current_episode}`; // Unique tag
        
        // for Facebook
        formData.append("access_token", process.env.TOKEN); // Facebook Page access token
        formData.append("published", "true"); // "false" for debugging
        formData.append("url", sxRes.url + ".jpeg");
        formData.append("caption", caption);
        
        // Create new feed on Facebook Page
        const res = await fetch(`https://graph.facebook.com/v18.0/me/photos`, {
            body: formData,
            method: "post"
        }).then(r => r.json());
        if (res.error) throw new Error(res.error.message);
        
        console.log(`Episode ${episodeWithPad} - Frame ${data.current_frame}/${data.max_frame} published!`);
        if (formData.get("published") == "false") console.log("Nah jk. It's not published lol.");
        
        // Update data
        updateData(data, dataPath);
        // Delete the frame
        fs.unlinkSync(framePath);
    } catch (err) {
        console.error(err.message);
        process.exit(1);
    }
})();

function updateData(data, dataPath) {
    data.current_frame++;
    fs.writeFileSync(dataPath, JSON.stringify(data, null, 2));
}